### ISSUE TITLE
Can't run the code

### ISSUE THREAD

**Issue by Zw1lling** [Zontex/red-alert#2]
Hey, I was trying to use your python code to make a Red Alert discord bot, but the code won't run and I don't understand the error.

Error:
```
Traceback (most recent call last):
  File "D:\Amit\RedAlert\DiscordBot\run.py", line 154, in <module>
    main()
  File "D:\Amit\RedAlert\DiscordBot\run.py", line 122, in main
    alert = RedAlert()
  File "D:\Amit\RedAlert\DiscordBot\run.py", line 19, in __init__
    self.locations = self.get_locations_list()
  File "D:\Amit\RedAlert\DiscordBot\run.py", line 84, in get_locations_list
    for line in csv:
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\encodings\cp1255.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1: character maps to <undefined>

Process finished with exit code 1
```

If you can help me it would be awesome!

**Comment by Zontex** [comment]
There are some new cities missing from the csv file, you can add them manually or wait for an update I'll update the csv file later on.

**Comment by Zw1lling** [comment]
I have no idea what cities are missing from the file so I will wait for your update later on. Thanks!
